# Generated by Django 5.1.3 on 2024-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insecureuser_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='insecureuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
